CREATE DATABASE gatesopenerdb;
GRANT ALL PRIVILEGES ON gatesopenerdb.* TO 'gatesopener'@'localhost' IDENTIFIED BY 'gopwd' WITH GRANT OPTION;
USE gatesopenerdb;


CREATE TABLE UTENTI(
   ID_UTENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   NOME VARCHAR(20),
   COGNOME VARCHAR(20),
   EMAIL VARCHAR(50),
   PASSWORD VARCHAR(20),
   IMEI VARCHAR(15),
   ABILITATO VARCHAR(2),
   MAIL_INVIATA VARCHAR(2),
   ADMINISTRATOR VARCHAR(20) DEFAULT 'NO'
);

CREATE TABLE LOG(
   ID_LOG INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   TIPO VARCHAR(50),
   MESSAGGIO VARCHAR(100),
   DATAORA TIMESTAMP,
   UTENTE INT,
  FOREIGN KEY(UTENTE) REFERENCES UTENTI(ID_UTENTE)
);

CREATE TABLE CONFIGURAZIONI(
   ID_CONF INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   TIPO VARCHAR(20),
   NOME VARCHAR(20),
   VALORE VARCHAR(50)
);

INSERT INTO CONFIGURAZIONI (TIPO,NOME,VALORE) VALUES('MAIL','INDIRIZZO','MAILGO');
INSERT INTO CONFIGURAZIONI (TIPO,NOME,VALORE) VALUES ('MAIL','PASSWORD','PWDGO');
INSERT INTO CONFIGURAZIONI (TIPO,NOME,VALORE) VALUES ('MAIL','SMTP','smtp.gmail.com');
INSERT INTO CONFIGURAZIONI (TIPO,NOME,VALORE) VALUES ('MAIL','PORTA','587');
INSERT INTO CONFIGURAZIONI (TIPO,NOME,VALORE) VALUES ('SERVER','LINK','http://IPRPI:5000/aggiungiNuovo/');

INSERT INTO UTENTI (NOME,COGNOME,EMAIL,PASSWORD,IMEI,ABILITATO,MAIL_INVIATA,ADMINISTRATOR) VALUES('NOMEADMIN','COGADMIN','MAILADMIN','PWDADMIN','IMEIADMIN','SI','NO','SI');
